apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel
  labels:
    app: hotel
spec:
  replicas: 1
  template:
    metadata:
      name: hotel
      labels:
        app: hotel
    spec:
      containers:
        - name: hotel
          image: alexius1905/hotel:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
          envFrom:
            - configMapRef:
                name: env-vars
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8087
            initialDelaySeconds: 50
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8087
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
      restartPolicy: Always
  selector:
    matchLabels:
      app: hotel