server:
  port: 8080

spring:
  application:
    name: user
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non-contextual-creation: true
  datasource:
    url: jdbc:postgresql://postgres/user
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    rest:
      base-path: /api
  security:
    filter:
      order: 10
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672

logging:
  level:
    root: WARN
    com.example.user: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: "*"
          show-details: always
        liveness:
          include: ping
          show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    enabled: false

clients:
  notification:
    url: http://notification:8081
  review:
    url: http://review:8084

myhostname: ${MY_HOST_NAME}

access.token.secret: ${ACCESS_TOKEN_SECRET}
refresh.token.secret: ${REFRESH_TOKEN_SECRET}

access.token.expiration: 60
refresh.token.expiration: 30

cookies.domain: localhost

application-version: 1.0.0