server:
  port: 8082

spring:
  application:
    name: restaurant
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non-contextual-creation: true
  datasource:
    url: jdbc:postgresql://postgres/restaurant
    username: postgres
    password: 1234
  data:
    rest:
      base-path: /api
  zipkin:
    base-url: http://zipkin:9411

logging:
  level:
    root: WARN
    com.example.restaurant: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

clients:
  auth:
   url: http://user:8080

application-version: 1.0.0