server:
  port: 8081

spring:
  application:
    name: notification
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non-contextual-creation: true
  datasource:
    url: jdbc:postgresql://postgres/notification
    username: postgres
    password: 1234
  data:
    rest:
      base-path: /api
  mail:
    host: smtp.yandex.ru
    username: maicl.svetlov@yandex.ru
    password: unevqrlqmgafiymw
    port: 465
    protocol: smtps
    properties:
      mail:
        debug: true

  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672

logging:
  level:
    root: WARN
    com.example.notification: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key