server:
  port: 8083
#  https://www.baeldung.com/spring-boot-https-self-signed-certificate
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/travel_expert.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: ${KEY_STORE_ALIAS}
#    enabled: true
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id: restaurant
          uri: lb://RESTAURANT
          predicates:
            - Path=/api/v1/restaurants/**
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/users/**, /api/v1/profile/**, /api/v1/auth/**
        - id: review
          uri: lb://REVIEW
          predicates:
            - Path=/api/v1/reviews/**
        - id: image
          uri: lb://IMAGE
          predicates:
            - Path=/api/v1/images/**
        - id: hotel
          uri: lb://HOTEL
          predicates:
            - Path=/api/v1/hotels/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true