server:
  port: 8085
spring:
  application:
    name: image
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non-contextual-creation: true
  datasource:
    url: jdbc:postgresql://postgres/image
    username: postgres
    password: 1234
  data:
    rest:
      base-path: /api
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    root: WARN
    com.example.image: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

clients:
  auth:
    url: http://user:8080

application-version: 1.0.0