server:
  port: 8085
spring:
  application:
    name: image
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non-contextual-creation: true
  datasource:
    url: jdbc:postgresql://postgres/image
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  data:
    rest:
      base-path: /api
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false

logging:
  level:
    root: WARN
    com.example.image: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: "*"
          show-details: always
        liveness:
          include: ping
          show-details: always

clients:
  auth:
    url: http://user:8080

application-version: 1.0.0