apiVersion: apps/v1
kind: Deployment
metadata:
  name: image
  labels:
    app: image
spec:
  replicas: 1
  template:
    metadata:
      name: image
      labels:
        app: image
    spec:
      containers:
        - name: image
          image: alexius1905/image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085
            initialDelaySeconds: 50
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8085
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
      restartPolicy: Always
  selector:
    matchLabels:
      app: image